// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnOB_e0z30vyIbMgAxh6FPm5zA46Zxh0o',
    appId: '1:988340059004:web:1b08c0e20da5734a0642f9',
    messagingSenderId: '988340059004',
    projectId: 'flutter-firebase-codelab-74d48',
    authDomain: 'flutter-firebase-codelab-74d48.firebaseapp.com',
    storageBucket: 'flutter-firebase-codelab-74d48.appspot.com',
    measurementId: 'G-BCMQYRGDNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvYbtsJpZMut2fIpqlkBUcXIAUQjkEfOY',
    appId: '1:988340059004:android:f26dabb241b1709a0642f9',
    messagingSenderId: '988340059004',
    projectId: 'flutter-firebase-codelab-74d48',
    storageBucket: 'flutter-firebase-codelab-74d48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2zpvxpBkagGpyPX5WdfQN3iD-sk_NpZM',
    appId: '1:988340059004:ios:e228492b90e4a7ab0642f9',
    messagingSenderId: '988340059004',
    projectId: 'flutter-firebase-codelab-74d48',
    storageBucket: 'flutter-firebase-codelab-74d48.appspot.com',
    iosClientId: '988340059004-udr9if3aovh2broo15k6v449nsptf7ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginAndDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2zpvxpBkagGpyPX5WdfQN3iD-sk_NpZM',
    appId: '1:988340059004:ios:e228492b90e4a7ab0642f9',
    messagingSenderId: '988340059004',
    projectId: 'flutter-firebase-codelab-74d48',
    storageBucket: 'flutter-firebase-codelab-74d48.appspot.com',
    iosClientId: '988340059004-udr9if3aovh2broo15k6v449nsptf7ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginAndDatabase',
  );
}
